[package]
name = "maths"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = [
	"add",
	"mul",
	"mul_assign",
], default-features = false }
micromath = "2.1.0"

[features]
std = []
