[package]
name = "rendy3d"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["deref", "deref_mut", "add"] }
stl_io = "0.8.5"
maths = { path = "../maths" }
obj-rs = "0.7.4"
image = "0.25.6"

[features]
default = ["std"]
std = []
