[package]
name = "web"
version = "0.1.0"
edition = "2024"
[[bin]]
name = "web_binary"
path = "src/main.rs"
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
softbuffer = "0.4.6"
winit = "0.30.12"
rendy3d = { path = "../crates/renderer" }
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
